# Generated by Django 5.1 on 2024-09-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_bookinstance_question_text_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='question_text',
        ),
    ]
